.PHONY: all clean

all:
	make -C osdep
	make -C thread
	make -C reentrant
	make -C mapcombine

clean:
	make -C osdep/ clean
	make -C thread/ clean
	make -C reentrant/ clean
	make -C mapcombine/ clean
